version: 1.1.2-beta.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
before_build:
- cmd: nuget restore src\Cogworks.Meganav.sln
build:
  project: src/Cogworks.Meganav.sln
  verbosity: minimal
